export const company = {
  name: "MakeWebb",
  tagline: "We build systems that ship",
  email: "hello.makewebb@gmail.com",
  github: "https://github.com/owaies/MakeWebb",
  website: "https://makewebb.vercel.app/",
};

export const services = [
  { id: "01", title: "Websites", blurb: "Fast, animated, SEO-ready websites that turn a sharp idea into a credible digital product.", tags: ["Next.js", "React", "Motion"], examples: ["Silsila Burqa House", "MakeWebb portfolio systems"] },
  { id: "02", title: "Applications", blurb: "Product-grade web and mobile experiences with real auth, data, dashboards, workflows and responsive UX.", tags: ["Next.js", "Web Apps", "Analytics"], examples: ["AI Job Tracker", "E-Examiner", "DocFlow"] },
  { id: "03", title: "AI Integration", blurb: "Useful AI inside products: assistants, extraction, search, generation, vision and intelligent decision support.", tags: ["Python", "LLMs", "Vision"], examples: ["AI Job Tracker", "AI Retail Shelf Intelligence", "World Object Detector", "Hand Gesture Controller", "DocFlow"] },
  { id: "04", title: "AI Automation", blurb: "Automated pipelines and agents that connect data, models and business workflows without adding manual overhead.", tags: ["Agents", "Data", "Workflows"], examples: ["Job tracking workflows", "Document workflows with DocFlow", "Retail vision pipelines", "Assessment operations"] },
  { id: "05", title: "UI/UX Design", blurb: "Clear, high-conversion product interfaces with thoughtful flows, interaction design and responsive systems.", tags: ["Product Design", "Prototyping", "Design Systems"], examples: ["AI Job Tracker", "E-Examiner", "MakeWebb product interfaces"] },
  { id: "06", title: "3D / Interactive Experiences", blurb: "Immersive web experiences with 3D visuals, motion, interactive storytelling and responsive spatial interfaces.", tags: ["3D", "WebGL", "Motion"], examples: ["Interactive portfolio experiences", "3D product showcases", "Cinematic web sections"] },
  { id: "07", title: "Analytics & Data", blurb: "Decision-ready dashboards and data experiences that turn product activity into signals teams can act on.", tags: ["Analytics", "Python", "Data"], examples: ["AI Job Tracker", "Retail intelligence", "Assessment analytics"] },
];

export const founders = [
  { name: "Mohammed Owaies", role: "AI/ML Engineer", focus: "AI · ML · DATA", portfolio: "https://owaies-portfolio.base44.app", github: "https://github.com/owaies", linkedin: "https://www.linkedin.com/in/mohammed-owaies-507b4a398", email: "owaies786@gmail.com", phone: "7619329863" },
  { name: "Mohammed Afaf Hassan", role: "Web Developer", focus: "WEB · APPS · UI/UX", portfolio: "https://afaf.base44.app", github: "https://github.com/afaf-app", linkedin: "https://www.linkedin.com/in/mansafaf", email: "kingahassan786@gmail.com", phone: "8073818817" },
];

export const projects = [
  { code: "MW / 001", name: "AI Job Tracker", type: "AI PRODUCT", categories: ["AI", "WEB APPS"], tech: "Next.js · Python/AI · Analytics", url: "https://ai-job-application-tracker-rose.vercel.app", eyebrow: "Turn a job hunt into a measurable pipeline", goal: "Give applicants one place to capture opportunities, follow application states and turn a scattered search into actionable analytics.", implementation: "Responsive product UI, structured application records, analytics views and AI-assisted workflow concepts designed around the real stages of a job search.", technologies: ["Next.js", "React", "AI", "Analytics", "Responsive UI"], outcomes: ["Application visibility", "Pipeline status tracking", "Analytics-ready workflow"], preview: "jobs" },
  { code: "MW / 002", name: "E-Examiner", type: "ASSESSMENT PLATFORM", categories: ["ASSESSMENT PLATFORMS", "WEB APPS"], tech: "Web App · Assessments · Exams", url: "https://e-examiner.vercel.app/", eyebrow: "A focused digital assessment experience", goal: "Move examinations into a structured online flow where learners can access assessments and administrators can manage the experience digitally.", implementation: "Assessment-first information architecture with exam flows, question presentation, responsive states and a foundation for results and administration workflows.", technologies: ["React", "Web Apps", "Assessments", "Forms", "Responsive UI"], outcomes: ["Digital exam delivery", "Structured assessment flow", "Result-ready data model"], preview: "exam" },
  { code: "MW / 003", name: "World Object Detector", type: "COMPUTER VISION", categories: ["AI", "COMPUTER VISION"], tech: "Python · Computer Vision · Detection", url: "https://world-object-detector.netlify.app/", eyebrow: "See and classify the world through a camera", goal: "Demonstrate practical computer vision by turning visual input into recognizable objects and useful detection output.", implementation: "Camera-oriented computer-vision pipeline with detection states, visual overlays and a web surface for interacting with model output.", technologies: ["Python", "Computer Vision", "Object Detection", "Web UI"], outcomes: ["Live visual inference", "Object-level detection", "Interactive camera workflow"], preview: "vision" },
  { code: "MW / 004", name: "Silsila Burqa House", type: "E-COMMERCE", categories: ["E-COMMERCE", "WEB APPS"], tech: "Web · Commerce · Product Experience", url: "https://silsilaburqahouse.web.app", eyebrow: "Commerce built around the product", goal: "Create a polished digital storefront that makes product discovery and purchase intent feel straightforward on every screen.", implementation: "Responsive storefront patterns, product-led presentation and conversion-focused navigation shaped around a real commerce catalogue.", technologies: ["Web", "Commerce", "Responsive UI", "Product UX"], outcomes: ["Product discovery", "Mobile-ready storefront", "Commerce-ready experience"], preview: "commerce" },
  { code: "MW / 005", name: "Hand Gesture Controller", type: "COMPUTER VISION", categories: ["AI", "COMPUTER VISION"], tech: "Python · Hand Tracking · Interaction", url: "https://handgesturecontroller.netlify.app/", eyebrow: "Turn hand movement into interface control", goal: "Explore a natural interaction layer where tracked hand gestures become intentional commands instead of mouse and keyboard input.", implementation: "Real-time hand-tracking concepts mapped to recognizable gesture states and browser-facing interaction feedback.", technologies: ["Python", "Hand Tracking", "Computer Vision", "Interaction"], outcomes: ["Gesture recognition", "Real-time interaction", "Camera-driven controls"], preview: "gesture" },
  { code: "MW / 006", name: "AI Retail Shelf Intelligence", type: "AI RETAIL / COMPUTER VISION", categories: ["AI", "COMPUTER VISION", "E-COMMERCE"], tech: "AI · Computer Vision · Retail Analytics", url: "https://ai-retail-shelf-intelligence.vercel.app/login", eyebrow: "Turn shelf imagery into retail intelligence", goal: "Help retail teams inspect shelf conditions through computer vision and convert visual store data into actionable product and merchandising insight.", implementation: "AI-powered retail interface centered on shelf-image analysis, visual recognition and intelligence workflows for understanding product presence and shelf conditions.", technologies: ["AI", "Computer Vision", "Retail Analytics", "Web App", "Vision Models"], outcomes: ["Shelf intelligence workflow", "Visual product recognition", "Retail analytics surface"], preview: "retail" },
  { code: "MW / 007", name: "DocFlow", type: "DOCUMENT AI / WORKFLOW", categories: ["AI", "WEB APPS"], tech: "AI · Document Processing · Workflow", url: "https://docflow-lyart-omega.vercel.app/", eyebrow: "Move documents from input to useful workflow", goal: "Create a focused workspace for handling documents with AI-assisted processing so information can move from files into structured, actionable workflows.", implementation: "Document-first product flow designed around file intake, AI-assisted understanding and organized workflow states for turning unstructured documents into usable information.", technologies: ["AI", "Document Processing", "Web Apps", "Workflow", "Data Extraction"], outcomes: ["Document processing workflow", "AI-assisted extraction", "Structured information flow"], preview: "docflow" },
];
