import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { Nav } from "../components/site/Nav";
import { Footer } from "../components/site/Footer";
import { SmoothScroll } from "../components/site/SmoothScroll";
import { SpecialCursor } from "../components/site/SpecialCursor";

const SITE_URL = "https://makewebb.vercel.app";
const SEO_DESCRIPTION = "MakeWebb is a digital product studio building websites, apps, AI integrations, automation, UI/UX and interactive 3D experiences. Search for MakeWebb, Make Webb or Make Web to find our official site.";

function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold text-foreground">404</h1><h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><div className="mt-6"><Link to="/" className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90">Go home</Link></div></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"});},[error]);return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold tracking-tight text-foreground">This page didn't load</h1><p className="mt-2 text-sm text-muted-foreground">Something went wrong on our end. You can try refreshing or head back home.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><button onClick={()=>{router.invalidate();reset();}} className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90">Try again</button><a href="/" className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent">Go home</a></div></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"MakeWebb | Websites, Apps, AI & Automation"},{name:"description",content:SEO_DESCRIPTION},{name:"author",content:"MakeWebb"},{name:"robots",content:"index, follow, max-image-preview:large"},{property:"og:title",content:"MakeWebb | Websites, Apps, AI & Automation"},{property:"og:description",content:SEO_DESCRIPTION},{property:"og:type",content:"website"},{property:"og:url",content:SITE_URL},{property:"og:site_name",content:"MakeWebb"},{name:"twitter:card",content:"summary_large_image"},{name:"twitter:title",content:"MakeWebb | Websites, Apps, AI & Automation"},{name:"twitter:description",content:SEO_DESCRIPTION}],links:[{rel:"canonical",href:SITE_URL},{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700&family=Manrope:wght@300;400;500;600&display=swap"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Organization",name:"MakeWebb",url:SITE_URL,description:SEO_DESCRIPTION,brand:{"@type":"Brand",name:"MakeWebb"},sameAs:["https://github.com/owaies/MakeWebb"]})}}/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><SmoothScroll><div className="site-content-layer"><Nav/><Outlet/><Footer/></div><SpecialCursor/></SmoothScroll></QueryClientProvider>}
