import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Reveal, RevealWords } from "@/components/site/Reveal";
import { TiltCard } from "@/components/site/TiltCard";
import { services } from "@/lib/site-data";

export const Route = createFileRoute("/services")({ head: () => ({ meta: [{ title: "Services — Websites, Apps, AI & Automation | MakeWebb" }, { name: "description", content: "MakeWebb services: website design and build, web and mobile applications, AI integration and business automation." }, { property: "og:title", content: "Services | MakeWebb" }, { property: "og:description", content: "Websites, applications, AI integration and automation, delivered end to end." }] }), component: ServicesPage });
const process=[{step:"01",title:"Scope",text:"A short call, a written plan, a fixed price and timeline."},{step:"02",title:"Design",text:"Interface and motion prototyped before a line of product code."},{step:"03",title:"Build",text:"Shipped in weekly slices you can click, not screenshots."},{step:"04",title:"Run",text:"Deploy, monitor, automate and keep improving after launch."}];
function ServicesPage(){return <main><section className="aurora grain px-5 pt-40 pb-24 md:px-10"><div className="mx-auto max-w-6xl"><p className="text-xs tracking-[0.3em] text-foreground/70 uppercase">Services</p><h1 className="text-huge mt-6 max-w-4xl"><RevealWords text="Everything from"/><span className="block text-foreground/45"><RevealWords text="idea to uptime"/></span></h1></div></section><section className="mx-auto max-w-6xl px-5 py-24 md:px-10"><div className="grid gap-5 md:grid-cols-2">{services.map((s,i)=><Reveal key={s.id} delay={i*.08}><TiltCard intensity={10} className="glass h-full p-8"><span className="font-display text-sm text-primary">{s.id}</span><h2 className="mt-8 text-3xl font-semibold">{s.title}</h2><p className="mt-3 text-sm text-muted-foreground">{s.blurb}</p><div className="mt-6 flex flex-wrap gap-2">{s.tags.map(t=><span key={t} className="rounded-full bg-secondary px-3 py-1 text-xs">{t}</span>)}</div></TiltCard></Reveal>)}</div></section><section className="mx-auto max-w-6xl px-5 pb-28 md:px-10"><Reveal><h2 className="text-big">How we work</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-4">{process.map((p,i)=><Reveal key={p.step} delay={i*.08}><div className="h-full rounded-2xl border border-border p-6"><span className="font-display text-xs text-primary">{p.step}</span><h3 className="mt-6 text-xl font-semibold">{p.title}</h3><p className="mt-2 text-sm text-muted-foreground">{p.text}</p></div></Reveal>)}</div><Reveal delay={.2} className="mt-14"><Link to="/contact" className="inline-flex items-center gap-2 rounded-full bg-foreground px-6 py-3 text-sm font-medium text-background">Start a project <ArrowRight className="h-4 w-4"/></Link></Reveal></section></main>}
