'use client';

import { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { animate } from 'animejs';

const BLUE=0x5b9cff,CYAN=0x62d7ff,VIOLET=0x9b7cff;
const PEOPLE=[
 {name:'Mohammed Owaies',role:'AI / ML Engineer',tag:'AI · ML · DATA',image:'/team/file_000000002d308211b0a2203107625baf.png',accent:BLUE},
 {name:'Mohammed Afaf Hassan',role:'Web Developer',tag:'WEB · APPS · UI/UX',image:'/team/file_000000001c20821185b00fb24f8c0312.png',accent:VIOLET},
] as const;

function roundedShape(w:number,h:number,r:number){const s=new THREE.Shape(),x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);return s;}
function infoTexture(p:typeof PEOPLE[number]){const c=document.createElement('canvas');c.width=900;c.height=350;const x=c.getContext('2d');if(!x)return new THREE.CanvasTexture(c);const col='#'+p.accent.toString(16).padStart(6,'0');x.fillStyle='#fff';x.font='800 48px Arial';x.fillText(p.name,28,58);x.fillStyle=col;x.font='700 28px Arial';x.fillText(p.role,28,101);x.fillStyle='#9badc0';x.font='500 19px Arial';x.fillText(p.tag,28,138);x.fillStyle='#64758b';x.font='500 15px Arial';x.fillText('PRODUCT · ENGINEERING · EXPERIENCE',28,174);x.fillStyle=col;x.fillRect(28,207,110,4);x.fillStyle='#263a51';x.fillRect(28,229,170,4);x.fillRect(28,251,135,4);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function makeProfile(p:typeof PEOPLE[number]){const g=new THREE.Group();const geo=new THREE.ExtrudeGeometry(roundedShape(3.25,5.05,.25),{depth:.28,bevelEnabled:true,bevelSegments:8,bevelSize:.08,bevelThickness:.075,curveSegments:12});geo.center();const body=new THREE.Mesh(geo,new THREE.MeshPhysicalMaterial({color:0x071321,transparent:true,opacity:.72,roughness:.13,metalness:.12,clearcoat:1,clearcoatRoughness:.03,side:THREE.DoubleSide}));g.add(body);g.add(new THREE.LineSegments(new THREE.EdgesGeometry(geo,18),new THREE.LineBasicMaterial({color:p.accent,transparent:true,opacity:.96})));const tex=new THREE.TextureLoader().load(p.image);tex.colorSpace=THREE.SRGBColorSpace;const photo=new THREE.Mesh(new THREE.PlaneGeometry(2.92,3.1),new THREE.MeshStandardMaterial({map:tex,roughness:.34}));photo.position.set(0,.67,.18);g.add(photo);const shade=new THREE.Mesh(new THREE.PlaneGeometry(2.92,3.1),new THREE.MeshBasicMaterial({color:0x06101c,transparent:true,opacity:.08,depthWrite:false}));shade.position.set(0,.67,.19);g.add(shade);const panel=new THREE.Mesh(new THREE.BoxGeometry(2.82,1.18,.08),new THREE.MeshStandardMaterial({color:0x020711,transparent:true,opacity:.92,roughness:.2}));panel.position.set(0,-1.48,.2);g.add(panel);const text=new THREE.Mesh(new THREE.PlaneGeometry(2.66,1.04),new THREE.MeshBasicMaterial({map:infoTexture(p),transparent:true}));text.position.set(-.02,-1.49,.25);g.add(text);return g;}
function makeObject(kind:'web'|'android'|'windows'|'ai'){const g=new THREE.Group();const mat=new THREE.MeshPhysicalMaterial({color:0x071423,transparent:true,opacity:.62,roughness:.07,metalness:.08,clearcoat:1});const edge=new THREE.LineBasicMaterial({color:kind==='ai'?VIOLET:BLUE,transparent:true,opacity:.95});if(kind==='web'){const m=new THREE.Mesh(new THREE.BoxGeometry(1.45,.84,.14),mat);g.add(m,new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),edge));for(let i=0;i<3;i++){const l=new THREE.Mesh(new THREE.BoxGeometry(.78-i*.1,.045,.02),new THREE.MeshBasicMaterial({color:i?0x7892b3:CYAN}));l.position.set(-.12,.16-i*.15,.1);g.add(l)}}if(kind==='android'){const m=new THREE.Mesh(new THREE.BoxGeometry(.76,1.38,.13),mat);g.add(m,new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),edge));const s=new THREE.Mesh(new THREE.PlaneGeometry(.6,1.12),new THREE.MeshBasicMaterial({color:0x0b2137}));s.position.z=.08;g.add(s)}if(kind==='windows'){const m=new THREE.Mesh(new THREE.BoxGeometry(1.15,1.15,.13),mat);g.add(m,new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),edge));const wm=new THREE.MeshBasicMaterial({color:BLUE,transparent:true,opacity:.78});for(let x=0;x<2;x++)for(let y=0;y<2;y++){const q=new THREE.Mesh(new THREE.PlaneGeometry(.37,.37),wm);q.position.set((x-.5)*.44,(y-.5)*.44,.08);g.add(q)}}if(kind==='ai'){const m=new THREE.Mesh(new THREE.BoxGeometry(1.08,1.08,.22),new THREE.MeshPhysicalMaterial({color:0x071321,transparent:true,opacity:.8,metalness:.15,roughness:.07,clearcoat:1}));g.add(m,new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),new THREE.LineBasicMaterial({color:VIOLET,transparent:true,opacity:.95})));const core=new THREE.Mesh(new THREE.BoxGeometry(.46,.46,.08),new THREE.MeshBasicMaterial({color:VIOLET,transparent:true,opacity:.8}));core.position.z=.14;g.add(core)}return g;}

export default function HeroThreeScene(){const host=useRef<HTMLDivElement>(null);useEffect(()=>{const el=host.current;if(!el)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.z=12.2;const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;el.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xc7ddf5,0x01050b,1.55));const key=new THREE.DirectionalLight(0xffffff,2.6);key.position.set(2,5,8);scene.add(key);const blue=new THREE.PointLight(BLUE,28,17,2);blue.position.set(-5,2,4);scene.add(blue);const violet=new THREE.PointLight(VIOLET,25,17,2);violet.position.set(5,-1,4);scene.add(violet);const cyan=new THREE.PointLight(CYAN,12,12,2);cyan.position.set(0,4,2);scene.add(cyan);
 const root=new THREE.Group();scene.add(root);const left=makeProfile(PEOPLE[0]),right=makeProfile(PEOPLE[1]);root.add(left,right);
 const center=new THREE.Group();root.add(center);const cubeMat=new THREE.MeshPhysicalMaterial({color:0x0a1b2d,transparent:true,opacity:.7,roughness:.045,metalness:.08,clearcoat:1,clearcoatRoughness:.02});const cube=new THREE.Mesh(new THREE.BoxGeometry(2.05,2.05,2.05),cubeMat);center.add(cube);const ce=new THREE.LineSegments(new THREE.EdgesGeometry(cube.geometry),new THREE.LineBasicMaterial({color:BLUE,transparent:true,opacity:1}));center.add(ce);const glowCube=new THREE.Mesh(new THREE.BoxGeometry(1.55,1.55,1.55),new THREE.MeshBasicMaterial({color:VIOLET,transparent:true,opacity:.055,wireframe:true}));center.add(glowCube);
 const lc=document.createElement('canvas');lc.width=500;lc.height=500;const cx=lc.getContext('2d');if(cx){cx.fillStyle='#8fc6ff';cx.shadowColor='#5b9cff';cx.shadowBlur=42;cx.font='900 118px Arial';cx.textAlign='center';cx.textBaseline='middle';cx.fillText('M/W',250,250)}const logoTex=new THREE.CanvasTexture(lc);logoTex.colorSpace=THREE.SRGBColorSpace;const logo=new THREE.Mesh(new THREE.PlaneGeometry(1.25,1.25),new THREE.MeshBasicMaterial({map:logoTex,transparent:true}));logo.position.z=1.06;center.add(logo);
 const ring=new THREE.Mesh(new THREE.TorusGeometry(2.8,.022,10,200),new THREE.MeshBasicMaterial({color:BLUE,transparent:true,opacity:.7}));ring.rotation.set(1.12,0,-.22);root.add(ring);const ring2=new THREE.Mesh(new THREE.TorusGeometry(2.2,.016,10,200),new THREE.MeshBasicMaterial({color:VIOLET,transparent:true,opacity:.5}));ring2.rotation.set(.3,1.08,.35);root.add(ring2);
 const serviceGroup=new THREE.Group();root.add(serviceGroup);(['web','android','windows','ai'] as const).forEach((kind,i)=>{const o=makeObject(kind);o.position.set(-4.55+i*3.05,-3.25,-.6);o.rotation.set(.12,.22+i*.12,-.04);o.scale.setScalar(1.05);serviceGroup.add(o);if(!reduced)animate(o.rotation,{y:[o.rotation.y-.12,o.rotation.y+.12],x:[o.rotation.x-.05,o.rotation.x+.05],duration:5000+i*450,alternate:true,loop:true,ease:'inOutSine'})});
 const fragments=new THREE.Group();root.add(fragments);for(let i=0;i<38;i++){const s=.055+(i%5)*.045;const m=new THREE.Mesh(new THREE.BoxGeometry(s,s,s),new THREE.MeshPhysicalMaterial({color:i%3===0?VIOLET:i%3===1?BLUE:CYAN,transparent:true,opacity:.34,roughness:.08,transmission:.25,clearcoat:1}));m.position.set((Math.random()-.5)*13,(Math.random()-.5)*8,-1-Math.random()*6);m.rotation.set(Math.random()*2,Math.random()*2,Math.random()*2);fragments.add(m)}
 const bigFragments=new THREE.Group();root.add(bigFragments);for(let i=0;i<10;i++){const s=.28+(i%3)*.18;const m=new THREE.Mesh(new THREE.BoxGeometry(s,s,s),new THREE.MeshPhysicalMaterial({color:i%2?BLUE:VIOLET,transparent:true,opacity:.16,roughness:.04,transmission:.38,clearcoat:1}));m.position.set((Math.random()-.5)*12,(Math.random()-.5)*7,-2-Math.random()*4);m.rotation.set(Math.random()*1.5,Math.random()*1.5,Math.random()*1.5);bigFragments.add(m)}
 const points=new Float32Array(900);for(let i=0;i<300;i++){points[i*3]=(Math.random()-.5)*15;points[i*3+1]=(Math.random()-.5)*9;points[i*3+2]=-2-Math.random()*7}const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(points,3));scene.add(new THREE.Points(pg,new THREE.PointsMaterial({color:CYAN,size:.024,transparent:true,opacity:.78})));
 const resize=()=>{const w=el.clientWidth||1,h=el.clientHeight||1,m=w<650;camera.aspect=w/h;camera.fov=m?43:34;camera.position.z=m?12.5:12.2;camera.updateProjectionMatrix();renderer.setSize(w,h,false);if(m){left.scale.setScalar(.56);right.scale.setScalar(.56);left.position.set(3.7,-3.7,-2.8);right.position.set(-3.7,-5.5,-3.2);left.rotation.set(.03,.08,-.02);right.rotation.set(.03,-.08,.02);center.position.set(0,3.05,1.3);center.scale.setScalar(1.02);ring.scale.setScalar(.9);ring2.scale.setScalar(.92);serviceGroup.visible=false;bigFragments.scale.setScalar(.9)}else{const s=w<1050?.9:1.08;left.scale.setScalar(.94*s);right.scale.setScalar(.94*s);left.position.set(-4.05,.3,.55);right.position.set(4.05,.3,.35);left.rotation.set(.035,.15,-.025);right.rotation.set(.035,-.15,.025);center.position.set(0,-1.45,1);center.scale.setScalar(1.04);ring.scale.setScalar(1);ring2.scale.setScalar(1);serviceGroup.visible=true;bigFragments.scale.setScalar(1)}};
 resize();const ro=new ResizeObserver(resize);ro.observe(el);const pointer={x:0,y:0};const move=(e:PointerEvent)=>{pointer.x=e.clientX/window.innerWidth-.5;pointer.y=e.clientY/window.innerHeight-.5};window.addEventListener('pointermove',move,{passive:true});let raf=0;const draw=()=>{root.rotation.y=pointer.x*.055;root.rotation.x=-pointer.y*.028;renderer.render(scene,camera);raf=requestAnimationFrame(draw)};draw();const motions:any[]=[];if(!reduced){motions.push(animate(left.position,{y:[left.position.y-.08,left.position.y+.1],z:[left.position.z-.12,left.position.z+.12],duration:7600,alternate:true,loop:true,ease:'inOutSine'}));motions.push(animate(right.position,{y:[right.position.y+.08,right.position.y-.07],z:[right.position.z-.1,right.position.z+.12],duration:8400,alternate:true,loop:true,ease:'inOutSine'}));motions.push(animate(center.position,{y:[center.position.y-.16,center.position.y+.13],duration:6200,alternate:true,loop:true,ease:'inOutSine'}));motions.push(animate(cube.rotation,{x:[-.34,-.18],y:[.4,.64],z:[-.1,.08],duration:7200,alternate:true,loop:true,ease:'inOutSine'}));motions.push(animate(glowCube.rotation,{x:[.2,.5],y:[-.3,.4],duration:9000,alternate:true,loop:true,ease:'inOutSine'}));motions.push(animate(ring.rotation,{z:[-.34,.28],duration:12000,alternate:true,loop:true,ease:'inOutSine'}));motions.push(animate(ring2.rotation,{z:[.6,-.38],duration:15000,alternate:true,loop:true,ease:'inOutSine'}))}return()=>{cancelAnimationFrame(raf);ro.disconnect();window.removeEventListener('pointermove',move);motions.forEach(a=>a?.pause?.());renderer.dispose();renderer.domElement.remove()};},[]);return <div ref={host} className="hero-three-scene" aria-hidden="true"/>;}
