'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { animate } from 'animejs'
import { Glass } from './Glass'
import { MotionSection } from './Motion'

const serviceData=[
{name:'Websites',icon:'◎',copy:'High-impact websites and web apps with sharp UX, responsive systems and production-ready performance.',capabilities:'UX/UI · Frontend · CMS · Motion',tech:'Next.js · React · TypeScript',time:'2–6 weeks'},
{name:'Android Apps',icon:'◈',copy:'Product-focused Android experiences designed for speed, clarity and real-world use.',capabilities:'Product UI · Native flows · APIs',tech:'Android · Kotlin · Firebase',time:'4–10 weeks'},
{name:'Windows Software',icon:'⊞',copy:'Focused desktop software that turns complex workflows into fast, useful tools.',capabilities:'Desktop UX · Automation · Data',tech:'.NET · Windows · APIs',time:'4–12 weeks'},
{name:'AI Systems',icon:'AI',copy:'Practical AI layers that make products smarter without turning the interface into a science fair.',capabilities:'ML · LLMs · Vision · Automation',tech:'Python · APIs · AI models',time:'3–10 weeks'},
{name:'Interactive 3D',icon:'✦',copy:'Spatial product experiences, WebGL scenes and visual systems that reward exploration.',capabilities:'WebGL · Shaders · Interaction',tech:'Three.js · R3F · GLSL',time:'3–8 weeks'}]
const projects=[['01','AI Job Tracker','AI-assisted job discovery, scoring and application workflow.','AI / PRODUCT'],['02','E-Examiner','A structured digital examination platform built for reliability.','EDTECH / WEB'],['03','World Object Detector','Computer vision experience for recognizing objects in real time.','AI / VISION'],['04','Silaia Burqa House','A premium fashion commerce experience with a refined visual system.','COMMERCE / BRAND'],['05','Hand Gesture Controller','Hands-free interaction experiments powered by vision and gesture tracking.','AI / INTERACTION']]

export function Marquee(){return <div className="marquee" aria-label="Capabilities"><div className="marquee-track">{Array.from({length:2}).flatMap((_,i)=>['ANDROID','WINDOWS','AI / ML','PRODUCT ENGINEERING','3D INTERACTION','WEB DESIGN'].map((x,j)=><span key={`${i}-${j}`}>✦ {x}</span>))}</div></div>}

export function Services(){const[selected,setSelected]=useState(0);useEffect(()=>{const el=document.querySelector<HTMLElement>('[data-service-detail]');if(el)animate(el,{opacity:[.2,1],translateX:[18,0],duration:460,ease:'out(3)'})},[selected]);return <MotionSection id="services" className="section services-section"><div className="section-head"><div><span className="section-kicker">01 / SERVICES</span><h2>One studio.<br/><span>Many surfaces.</span></h2></div><p>Explore the capabilities behind the build. Select a service to see what we ship, how we build it and how long it typically takes.</p></div><div className="service-module"><div className="service-list">{serviceData.map((s,i)=><button key={s.name} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><span>0{i+1}</span><b>{s.icon}</b><strong>{s.name}</strong><span>↗</span></button>)}</div><Glass className="service-detail" data-service-detail><div className="module-top"><span>{`0${selected+1}`} / SERVICE MODULE</span><b>{serviceData[selected].icon}</b></div><h3>{serviceData[selected].name}</h3><p>{serviceData[selected].copy}</p><div className="detail-grid"><div><small>CAPABILITIES</small><b>{serviceData[selected].capabilities}</b></div><div><small>TECHNOLOGY</small><b>{serviceData[selected].tech}</b></div><div><small>ESTIMATED TIMELINE</small><b>{serviceData[selected].time}</b></div><div><small>STATUS</small><b>● Accepting selected builds</b></div></div></Glass></div></MotionSection>}

export function Projects(){const[selected,setSelected]=useState(0);const project=projects[selected];return <MotionSection id="projects" className="section projects-section"><div className="section-head"><div><span className="section-kicker">02 / PROJECTS</span><h2>Work with <span>depth.</span></h2></div><p>Selected product work across AI, commerce, education, computer vision and interaction.</p></div><div className="project-layout"><div className="project-list">{projects.map((p,i)=><button key={p[1]} onClick={()=>setSelected(i)} className={i===selected?'selected':''}><span>{p[0]}</span><strong>{p[1]}</strong><small>{p[3]}</small><i>↗</i></button>)}</div><Glass className="project-preview"><div className="preview-orbit"><div className="preview-cube"><span>{project[0]}</span><b>{project[1].split(' ').map(w=>w[0]).join('').slice(0,3)}</b></div></div><div className="preview-copy"><span>{project[3]}</span><h3>{project[1]}</h3><p>{project[2]}</p><Link href="#contact" className="text-link">Discuss a similar build ↗</Link></div></Glass></div></MotionSection>}

export function Technology(){const tech=['Next.js','React','Three.js','TypeScript','Node.js','Supabase','AI / ML'];return <MotionSection id="technology" className="section technology-section"><div className="section-head"><div><span className="section-kicker">03 / TECHNOLOGY</span><h2>The stack <span>orbits.</span></h2></div><p>A compact build system where product thinking, engineering and visual interaction share the same center of gravity.</p></div><div className="orbit-system"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="orbit-core"><span>M</span><small>MAKEWEBB<br/>BUILD SYSTEM</small></div>{tech.map((x,i)=><div className="tech-node" style={{'--i':i} as React.CSSProperties} key={x}>{x}</div>)}</div></MotionSection>}

export function AboutTeam(){return <MotionSection id="team" className="section about-section"><div className="about-grid"><div><span className="section-kicker">04 / STUDIO</span><h2>People.<br/><span>Ideas.</span><br/>Technology.<br/><span>Impact.</span></h2></div><Glass className="about-panel"><span>THE STUDIO</span><h3>Small team. Serious builds.</h3><p>MakeWebb turns early ideas into usable digital products. We combine product strategy, interface design, engineering, AI and 3D interaction into one continuous build process.</p><div className="stat-row"><b><span>02</span> founders</b><b><span>05</span> build surfaces</b><b><span>01</span> shared system</b></div></Glass></div><div className="team-cards"><Glass><span>CO-FOUNDER / AI · ML</span><h3>Mohammed Owaies</h3><p>AI/ML Engineer building intelligent product systems.</p><Link href="#contact">View profile ↗</Link></Glass><Glass><span>CO-FOUNDER / WEB</span><h3>Mohammed Afaf Hassan</h3><p>Web Developer shaping modern interfaces and product experiences.</p><Link href="#contact">View profile ↗</Link></Glass></div></MotionSection>}

export function Contact(){return <MotionSection id="contact" className="section contact-section"><Glass className="contact-panel"><div><span className="section-kicker">05 / CONTACT</span><h2>Have an idea?<br/><span>Let&apos;s build it.</span></h2><p>Tell us what you&apos;re making, what needs to work and where you want to take it.</p></div><div className="contact-actions"><a className="button button-primary" href="mailto:owaies786@gmail.com">Start a conversation ↗</a><div><span>owaies786@gmail.com</span><span>7619329863</span></div></div></Glass></MotionSection>}
