import React,{useEffect,useRef,useState}from'react';import{motion,useMotionValue,useSpring,useTransform}from'motion/react';import{ArrowUpRight,Menu,X,Github,Linkedin,Mail,Phone}from'lucide-react';
const projects=[['01','AI JOB TRACKER','AI PRODUCT','Next.js · AI · Analytics','https://ai-job-application-tracker-rose.vercel.app'],['02','E-EXAMINER','EXAM PLATFORM','Web App · Assessments · Exams','https://e-examiner.vercel.app/'],['03','WORLD OBJECT DETECTOR','COMPUTER VISION','Python · Vision · Detection','https://world-object-detector.netlify.app/'],['04','SILSILA BURQA HOUSE','E-COMMERCE','Web · Commerce · Product Experience','https://silsilaburqahouse.web.app'],['05','HAND GESTURE CONTROLLER','COMPUTER VISION','Python · Hand Tracking · Interaction','https://handgesturecontroller.netlify.app/']];
const skills=['AI','MACHINE LEARNING','DATA','WEB','APPS','UI/UX','COMPUTER VISION','INTERACTIVE EXPERIENCES'];
const usePointer=()=>{const x=useMotionValue(0),y=useMotionValue(0);const sx=useSpring(x,{stiffness:70,damping:20}),sy=useSpring(y,{stiffness:70,damping:20});useEffect(()=>{const f=(e:MouseEvent)=>{x.set((e.clientX/innerWidth-.5)*20);y.set((e.clientY/innerHeight-.5)*14)};addEventListener('mousemove',f);return()=>removeEventListener('mousemove',f)},[]);return[sx,sy]as const};
function Device({i}:{i:number}){return <motion.div className={'ref-device d'+i} whileHover={{y:-18,rotateY:i===1?0:5,rotateZ:i===0?-2:2}}><div className="device-screen"><small>{i===1?'MAKEWEBB':'MW / 00'+i}</small><b>{i===1?'SYSTEMS THAT ANSWER FIRST':i===2?'E-EXAMINER':'INTELLIGENT'}</b><span/></div></motion.div>}
function Chrome(){return <motion.div className="ref-chrome" animate={{rotateZ:[0,5,-4,0],rotateX:[0,8,-6,0],y:[0,-16,0]}} transition={{duration:8,repeat:Infinity,ease:'easeInOut'}}><div/></motion.div>}
function Founder({name,role,focus,img,portfolio,github,linkedin,email,phone}:{name:string;role:string;focus:string;img:string;portfolio:string;github:string;linkedin:string;email:string;phone:string}){return <article className="ref-founder"><div className="founder-image"><img src={img}alt={name}/></div><div className="founder-info"><span className="ref-meta">FOUNDER</span><h3>{name}</h3><p>{role} · {focus}</p><div><a href={portfolio}target="_blank">PORTFOLIO ↗</a><a href={github}target="_blank"><Github size={14}/></a><a href={linkedin}target="_blank"><Linkedin size={14}/></a><a href={'mailto:'+email}><Mail size={14}/></a><a href={'tel:'+phone}><Phone size={14}/></a></div></div></article>}
function Work(){const r=useRef<HTMLDivElement>(null);const[t,setT]=useState(0);useEffect(()=>{const f=()=>{if(!r.current)return;const b=r.current.getBoundingClientRect();setT(Math.max(0,Math.min(1,(innerHeight*.72-b.top)/(b.height-innerHeight*.45))))};addEventListener('scroll',f,{passive:true});f();return()=>removeEventListener('scroll',f)},[]);return <section id="projects" ref={r} className="match-work"><div className="match-sticky"><div className="ref-meta">SELECTED WORK</div><div className="match-canvas"><div className="match-track" style={{transform:`translate3d(${38-t*72}vw,0,0)`}}>{projects.map((p,i)=><a href={p[4]}target="_blank"rel="noreferrer"className={'match-card '+(i===2?'active':'')}key={p[0]} style={{transform:`translateY(${Math.sin(i*1.8+t*3)*12}px) scale(${i===2?.1:1-.08*Math.min(2,Math.abs(i-2))}) rotate(${(i-2)*1.5}deg)`,opacity:1-.16*Math.min(2,Math.abs(i-2))}}><small>#{p[0]}</small><h3>{p[1]}</h3><p>{p[2]} <i>|</i> {p[3]}</p><div className="preview"><div><span>{i===0?'AI':i===1?'EXAM':i===2?'NOVA':'MW'}</span><b>{p[1]}</b></div></div><strong>VIEW PROJECT <ArrowUpRight size={12}/></strong></a>)}</div></div><div className="archive">SEE THE FULL <b>ARCHIVE ↗</b></div></div></section>}
export default function ReferenceMatch(){const[menu,setMenu]=useState(false),[loading,setLoading]=useState(true);const[mx,my]=usePointer();const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};useEffect(()=>{const t=setTimeout(()=>setLoading(false),850);return()=>clearTimeout(t)},[]);return <div className="match-page">{loading&&<motion.div className="match-loader"exit={{opacity:0}}><span>MW</span><b>MAKEWEBB</b><small>DIGITAL PRODUCT STUDIO</small></motion.div>}<motion.header className="match-nav"style={{x:useTransform(mx,[-20,20],[-2,2]),y:useTransform(my,[-14,14],[-1,1])}}><button onClick={()=>go('hero')}className="brand"><span>MW</span>MAKEWEBB</button><nav>{[['projects','WORK'],['capabilities','CAPABILITIES'],['founders','FOUNDERS'],['contact','CONTACT']].map(([id,label])=><button key={id}onClick={()=>go(id)}>{label}</button>)}</nav><button className="nav-start"onClick={()=>go('contact')}>GET STARTED</button><button className="menu-btn"onClick={()=>setMenu(true)}><Menu size={16}/></button></motion.header>{menu&&<motion.div className="match-menu"initial={{opacity:0}}animate={{opacity:1}}><button onClick={()=>setMenu(false)}><X/></button><div>{['projects','capabilities','founders','contact'].map(x=><button key={x}onClick={()=>go(x)}>{x.toUpperCase()}</button>)}</div></motion.div>}
<section id="hero"className="match-hero"><div className="hero-grid"><div className="hero-copy"><span className="ref-meta white">MW / 001 · DIGITAL PRODUCT STUDIO</span><h1>SYSTEMS THAT<br/><em>ANSWER FIRST.</em></h1><p>Intelligent products, web experiences and data systems built for the next layer of the web.</p><div><button onClick={()=>go('projects')}>VIEW WORK ↗</button><button onClick={()=>go('founders')}>MEET THE FOUNDERS ↓</button></div></div><motion.div className="device-stage"style={{x:mx,y:my}}><Device i={0}/><Device i={1}/><Device i={2}/></motion.div></div><div className="star">✦</div><div className="hero-bottom ref-meta white"><span>AI · WEB · DATA · EXPERIENCE</span><span>SCROLL / EXPLORE</span></div></section>
<section className="match-light manifesto"><span className="ref-meta">MW / 002 · STUDIO</span><div className="manifesto-copy"><h2>WE DON'T JUST<br/>BUILD WEBSITES.</h2><div className="manifesto-devices"><Device i={0}/><Device i={1}/><Device i={2}/></div></div></section>
<section id="capabilities"className="match-dark capability"><span className="ref-meta white">MW / 003 · CAPABILITIES</span><div className="cap-head">BEYOND<br/><span>EVERY LIMIT.</span></div><div className="cap-grid">{skills.map((s,i)=><motion.div key={s}whileInView={{opacity:[0,.4,1],y:[24,0]}}viewport={{once:true}}transition={{duration:.7,delay:i*.04}}><small>0{i+1}</small><b>{s}</b><span>{i%2?'SYSTEMS':'PRODUCT'} · 2026</span></motion.div>)}</div></section>
<Work/>
<section id="founders"className="match-light founders"><span className="ref-meta">MW / 005 · FOUNDERS</span><div className="founder-grid"><Founder name="MOHAMMED OWAIES"role="AI / ML ENGINEER"focus="AI · ML · DATA"img="/founders/owaies.png"portfolio="https://owaies-portfolio.base44.app"github="https://github.com/owaies"linkedin="https://www.linkedin.com/in/mohammed-owaies-507b4a398"email="owaies786@gmail.com"phone="7619329863"/><Founder name="MOHAMMED AFAF HASSAN"role="WEB DEVELOPER"focus="WEB · APPS · UI/UX"img="/founders/afaf.png"portfolio="https://afaf.base44.app"github="https://github.com/afaf-app"linkedin="https://www.linkedin.com/in/mansafaf"email="kingahassan786@gmail.com"phone="8073818817"/></div></section>
<section className="match-dark statement"><span className="ref-meta white">MW / 006 · STUDIO</span><h2>BUILD<br/><span>BEYOND</span><br/>EVERY LIMIT.</h2></section>
<section className="match-purple tech"><span className="ref-meta white">MW / 007 · TECHNOLOGY</span><div>{['AI','ML','DATA','PYTHON','NEXT.JS','REACT','JAVASCRIPT','COMPUTER VISION','UI/UX','WEB','APPS','AUTOMATION'].map(x=><b key={x}>{x}</b>)}</div></section>
<section id="contact"className="match-cta"><div><span className="ref-meta white">MW / 008 · CONTACT</span><h2>BUILD BEYOND<br/><em>EVERY LIMIT.</em></h2><p>Have an idea? Let's build the experience it deserves.</p><button onClick={()=>location.href='mailto:owaies786@gmail.com'}>START A PROJECT ↗</button></div><Chrome/></section><footer className="match-footer"><b>MAKEWEBB</b><span>DIGITAL PRODUCT STUDIO</span><span>AI · WEB · DATA · EXPERIENCE</span><span>© 2026 MAKEWEBB</span></footer></div>}
