import React, { useEffect, useRef, useState } from 'react';
import { motion, useMotionValue, useSpring, useTransform } from 'motion/react';
import { ArrowUpRight, Menu, X, Github, Linkedin, Mail, Phone } from 'lucide-react';

const projects = [
  ['MW / 001','AI JOB TRACKER','AI PRODUCT','Next.js · AI · Analytics','https://ai-job-application-tracker-rose.vercel.app'],
  ['MW / 002','E-EXAMINER','EXAM PLATFORM','Web App · Assessments · Exams','https://e-examiner.vercel.app/'],
  ['MW / 003','WORLD OBJECT DETECTOR','COMPUTER VISION','Python · Vision · Detection','https://world-object-detector.netlify.app/'],
  ['MW / 004','SILSILA BURQA HOUSE','E-COMMERCE','Web · Commerce · Product Experience','https://silsilaburqahouse.web.app'],
  ['MW / 005','HAND GESTURE CONTROLLER','COMPUTER VISION','Python · Hand Tracking · Interaction','https://handgesturecontroller.netlify.app/'],
];

const capabilities = [
  ['01','AI / MACHINE LEARNING','Intelligent systems designed to transform complex data into useful decisions.','Python · AI · ML · Data'],
  ['02','DATA SYSTEMS','High-throughput pipelines, vector search and analytical telemetry.','Vector DB · SQL · RAG'],
  ['03','COMPUTER VISION','Real-time optical feeds, detection and hand tracking.','OpenCV · PyTorch · YOLO'],
  ['04','WEB APPLICATIONS','Fast React platforms with fluid UX and resilient architecture.','Next.js · React · TypeScript'],
  ['05','UI / UX','Human-centered interfaces, typography systems and motion.','Figma · Systems · Motion'],
  ['06','INTERACTIVE EXPERIENCES','WebGL, 3D objects and continuous scroll choreography.','Three.js · WebGL · Motion'],
  ['07','AUTOMATION','Autonomous services and operational pipelines.','Workers · Events · Cloud'],
  ['08','DIGITAL PRODUCTS','From prototype to production, end to end.','Full-stack · Cloud · Scale'],
];

function useMagnet(strength=14){
  const x=useMotionValue(0), y=useMotionValue(0);
  const sx=useSpring(x,{stiffness:240,damping:18}), sy=useSpring(y,{stiffness:240,damping:18});
  return {x:sx,y:sy, handlers:{onPointerMove:(e:any)=>{const r=e.currentTarget.getBoundingClientRect();x.set(((e.clientX-r.left)/r.width-.5)*strength);y.set(((e.clientY-r.top)/r.height-.5)*strength)},onPointerLeave:()=>{x.set(0);y.set(0)}}};
}

export default function ReferenceRebuild(){
  const [menu,setMenu]=useState(false); const [loaded,setLoaded]=useState(false); const [dark,setDark]=useState(false);
  const cursorX=useMotionValue(0), cursorY=useMotionValue(0); const cx=useSpring(cursorX,{stiffness:400,damping:35}), cy=useSpring(cursorY,{stiffness:400,damping:35});
  useEffect(()=>{const m=(e:MouseEvent)=>{cursorX.set(e.clientX);cursorY.set(e.clientY)};window.addEventListener('mousemove',m);const t=setTimeout(()=>setLoaded(true),1100);return()=>{window.removeEventListener('mousemove',m);clearTimeout(t)}},[]);
  const scrollTo=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};
  const button=useMagnet(9);
  return <div className={dark?'bg-[#08070b] text-white min-h-screen':'bg-[#f4f3f7] text-[#09090b] min-h-screen'}>
    {!loaded&&<div className="fixed inset-0 z-[100] bg-[#09070e] text-white flex items-center justify-center"><motion.div initial={{opacity:0,scale:.85}} animate={{opacity:1,scale:1}} transition={{duration:.5}} className="text-center"><div className="text-[11px] font-mono tracking-[.35em]">MW</div><div className="mt-3 font-display text-4xl tracking-[-.04em]">MAKEWEBB</div><div className="mt-2 mini text-white/50">DIGITAL PRODUCT STUDIO</div></motion.div></div>}
    <motion.div className="hidden lg:block fixed z-[90] pointer-events-none rounded-full border border-[#7d43da]/70 w-7 h-7 -ml-3.5 -mt-3.5" style={{x:cx,y:cy}} />
    <header className="fixed z-50 top-4 left-1/2 -translate-x-1/2 w-[calc(100%-28px)] max-w-5xl">
      <div className={`nav-pill rounded-full h-12 px-3 flex items-center justify-between ${dark?'dark-nav':''}`}>
        <button onClick={()=>scrollTo('hero')} className="flex items-center gap-2 px-2"><span className="w-7 h-7 rounded-full bg-[#17111f] text-white flex items-center justify-center mini tracking-[.08em]">MW</span><span className="font-semibold tracking-[.16em] text-[11px]">MAKEWEBB</span></button>
        <nav className="hidden md:flex items-center gap-6 mini"><button onClick={()=>scrollTo('projects')}>WORK</button><button onClick={()=>scrollTo('capabilities')}>CAPABILITIES</button><button onClick={()=>scrollTo('founders')}>FOUNDERS</button><button onClick={()=>scrollTo('studio')}>STUDIO</button></nav>
        <div className="flex items-center gap-2"><button className="hidden sm:block mini opacity-60" onClick={()=>setDark(!dark)}>{dark?'LIGHT':'DARK'}</button><button style={{transform:'translateZ(0)'}} {...button.handlers} onClick={()=>scrollTo('contact')} className="bg-[#0c0b0f] text-white dark:bg-white dark:text-black rounded-full px-4 py-2 mini">CONTACT ↗</button><button onClick={()=>setMenu(true)} className="md:hidden w-9 h-9 rounded-full border border-black/10 dark:border-white/15 flex items-center justify-center"><Menu size={15}/></button></div>
      </div>
    </header>
    {menu&&<div className="fixed inset-0 z-[80] bg-[#f4f3f7] p-6 flex flex-col dark:bg-[#09070e] dark:text-white"><div className="flex justify-between"><div className="mini">MW / DIRECTORY</div><button onClick={()=>setMenu(false)}><X/></button></div><div className="my-auto flex flex-col gap-5 font-display text-5xl tracking-[-.06em]"><button onClick={()=>scrollTo('projects')}>WORK</button><button onClick={()=>scrollTo('capabilities')}>CAPABILITIES</button><button onClick={()=>scrollTo('founders')}>FOUNDERS</button><button onClick={()=>scrollTo('studio')}>STUDIO</button><button onClick={()=>scrollTo('contact')}>CONTACT ↗</button></div></div>}

    <main>
      <section id="hero" className="scene-purple grain relative min-h-[100svh] overflow-hidden px-6 sm:px-10 pt-28 pb-10 flex flex-col justify-between">
        <div className="max-w-6xl w-full mx-auto mini text-white/75 flex justify-between"><span>MW / 001 · DIGITAL PRODUCT STUDIO</span><span className="hidden sm:block">AI · WEB · DATA</span></div>
        <div className="max-w-6xl w-full mx-auto grid lg:grid-cols-[1.25fr_.75fr] items-center gap-10">
          <div><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.25}} className="mini text-white/65 mb-5">SYSTEMS THAT ANSWER FIRST</motion.p><motion.h1 initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{delay:.35,duration:.9}} className="font-display font-semibold text-[clamp(4rem,10vw,9rem)] leading-[.82] hero-word text-white">MAKE<br/><span className="text-white/60">WEBB</span></motion.h1><p className="mt-8 max-w-xl text-white/78 text-sm sm:text-base leading-7">We build intelligent digital products that combine AI, data, interaction and immaculate web craft.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>scrollTo('projects')} className="rounded-full bg-white text-black px-5 py-3 mini">VIEW WORK ↗</button><button onClick={()=>scrollTo('founders')} className="rounded-full border border-white/25 bg-white/10 text-white px-5 py-3 mini">MEET THE FOUNDERS ↓</button></div></div>
          <div className="flex justify-center lg:justify-end"><motion.div animate={{rotate:360, y:[0,-14,0]}} transition={{rotate:{duration:18,repeat:Infinity,ease:'linear'},y:{duration:5,repeat:Infinity,ease:'easeInOut'}}} className="liquid-orb relative shadow-2xl" /></div>
        </div>
        <div className="max-w-6xl w-full mx-auto flex justify-between mini text-white/55"><span>SCROLL / EXPLORE</span><span>2026</span></div>
      </section>

      <section id="studio" className="scene-light relative min-h-[125svh] px-6 sm:px-10 py-28 overflow-hidden">
        <div className="max-w-6xl mx-auto"><div className="mini opacity-50 mb-20">MW / 002 · MANIFESTO</div><div className="space-y-2 font-display font-medium editorial-title text-[clamp(3.2rem,8.8vw,9rem)] leading-[.86]"><motion.div whileInView={{x:[-50,0],opacity:[0,1]}} viewport={{once:true}} transition={{duration:.7}}>WE DON'T JUST</motion.div><motion.div whileInView={{x:[50,0],opacity:[0,1]}} viewport={{once:true}} transition={{duration:.7,delay:.1}}>BUILD WEBSITES.</motion.div><motion.div className="text-[#7650ae]" whileInView={{y:[45,0],opacity:[0,1]}} viewport={{once:true}} transition={{duration:.7,delay:.2}}>WE BUILD</motion.div><motion.div whileInView={{y:[45,0],opacity:[0,1]}} viewport={{once:true}} transition={{duration:.7,delay:.3}}>INTELLIGENT</motion.div><motion.div whileInView={{y:[45,0],opacity:[0,1]}} viewport={{once:true}} transition={{duration:.7,delay:.4}}>PRODUCTS.</motion.div></div></div><div className="absolute right-10 bottom-16 mini opacity-45 max-w-xs">IDEAS → INTERFACES → SYSTEMS → EXPERIENCES</div>
      </section>

      <section id="capabilities" className="scene-dark min-h-screen px-6 sm:px-10 py-24"><div className="max-w-6xl mx-auto"><div className="flex justify-between mb-16"><div className="mini text-white/45">MW / 003 · CAPABILITIES</div><div className="mini text-white/35">08 SYSTEMS</div></div><div className="divide-y divide-white/10">{capabilities.map((c,i)=><motion.div key={c[0]} initial={{opacity:0,y:25}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-10%'}} transition={{delay:i*.04}} className="py-7 flex flex-col md:grid md:grid-cols-[60px_1.3fr_.9fr] gap-5 items-start md:items-center group"><span className="mini text-white/30">{c[0]}</span><h3 className="font-display text-2xl sm:text-4xl tracking-[-.04em] group-hover:translate-x-2 transition-transform">{c[1]}</h3><div><p className="text-sm text-white/55 max-w-md">{c[2]}</p><span className="mini text-[#b78aff] mt-3 inline-block">{c[3]}</span></div></motion.div>)}</div></div></section>

      <section id="projects" className="scene-light min-h-screen px-6 sm:px-10 py-28"><div className="max-w-6xl mx-auto"><div className="mini opacity-50 mb-6">MW / 004 · SELECTED WORK</div><h2 className="font-display text-[clamp(3.6rem,8vw,8rem)] editorial-title leading-[.84]">WORK<br/><span className="text-[#7650ae]">IN MOTION.</span></h2><div className="mt-20 space-y-8">{projects.map((p,i)=><a key={p[0]} href={p[4]} target="_blank" rel="noreferrer" className="project-shell group block rounded-[28px] overflow-hidden border border-black/10 bg-white/60"><div className="grid lg:grid-cols-[.9fr_1.1fr] min-h-[310px]"><div className="p-7 sm:p-10 flex flex-col justify-between"><div><div className="mini opacity-45">{p[0]}</div><h3 className="font-display text-4xl sm:text-6xl tracking-[-.055em] leading-[.86] mt-8">{p[1]}</h3></div><div className="mt-10"><div className="mini text-[#6d36bd]">{p[2]}</div><div className="mt-2 text-sm opacity-55">{p[3]}</div><div className="mt-5 mini">VIEW PROJECT <ArrowUpRight size={13} className="inline ml-1"/></div></div></div><div className="relative min-h-[250px] bg-gradient-to-br from-[#130b1f] via-[#53209c] to-[#d6c3f5] overflow-hidden"><div className="absolute inset-[12%] rounded-[22px] border border-white/30 bg-white/10 backdrop-blur-md rotate-[-6deg] group-hover:rotate-[-2deg] group-hover:scale-[1.04] transition duration-700"/><div className="absolute left-[18%] top-[26%] font-display text-white text-4xl opacity-90">{i%2===0?'SYSTEM':'SURFACE'}</div><div className="absolute right-[10%] bottom-[10%] w-28 h-28 rounded-full bg-white/15 blur-2xl"/></div></div></a>)}</div></div></section>

      <section id="founders" className="scene-dark px-6 sm:px-10 py-28 min-h-screen"><div className="max-w-6xl mx-auto"><div className="mini text-white/45 mb-12">MW / 005 · FOUNDERS</div><div className="grid lg:grid-cols-2 gap-8"><Founder name="MOHAMMED OWAIES" role="AI / ML ENGINEER" focus="AI · ML · DATA" img="/founders/owaies.jpg" portfolio="https://owaies-portfolio.base44.app" github="https://github.com/owaies" linkedin="https://www.linkedin.com/in/mohammed-owaies-507b4a398" email="owaies786@gmail.com" phone="7619329863"/><Founder name="MOHAMMED AFAF HASSAN" role="WEB DEVELOPER" focus="WEB · APPS · UI/UX" img="/founders/afaf.jpg" portfolio="https://afaf.base44.app" github="https://github.com/afaf-app" linkedin="https://www.linkedin.com/in/mansafaf" email="kingahassan786@gmail.com" phone="8073818817"/></div></div></section>

      <section className="scene-light px-6 sm:px-10 py-32 min-h-[90svh]"><div className="max-w-6xl mx-auto"><div className="mini opacity-45 mb-14">MW / 006 · PHILOSOPHY</div><div className="font-display text-[clamp(3.4rem,8.4vw,8.5rem)] leading-[.83] editorial-title">IDEAS<br/>DESERVE<br/><span className="text-[#7650ae]">BETTER</span><br/>INTERFACES.</div></div></section>

      <section className="scene-purple grain px-6 sm:px-10 py-28 min-h-[75svh]"><div className="max-w-6xl mx-auto"><div className="mini text-white/55 mb-16">MW / 007 · TECHNOLOGY</div><div className="flex flex-wrap gap-x-7 gap-y-2 font-display text-[clamp(2.7rem,7vw,7rem)] leading-[.88] editorial-title">{['AI','ML','DATA','PYTHON','NEXT.JS','REACT','JAVASCRIPT','COMPUTER VISION','UI/UX','WEB','APPS','AUTOMATION'].map((t,i)=><span key={t} className={i%4===0?'text-white/60':''}>{t}</span>)}</div></div></section>

      <section id="contact" className="scene-dark grain min-h-[90svh] px-6 sm:px-10 py-28 flex flex-col justify-between"><div className="max-w-6xl mx-auto w-full"><div className="mini text-white/40">MW / 008 · CONTACT</div><h2 className="mt-16 font-display text-[clamp(4rem,10vw,10rem)] leading-[.8] editorial-title">LET'S MAKE<br/><span className="text-[#b77bff]">SOMETHING</span><br/>WORTH<br/>SCROLLING FOR.</h2><div className="mt-12 flex flex-wrap gap-3"><a href="mailto:owaies786@gmail.com" className="rounded-full bg-white text-black px-5 py-3 mini">START A PROJECT ↗</a><a href="mailto:kingahassan786@gmail.com" className="rounded-full border border-white/20 px-5 py-3 mini">EMAIL US</a></div></div><footer className="max-w-6xl mx-auto w-full mt-20 pt-8 border-t border-white/10 grid sm:grid-cols-2 lg:grid-cols-4 gap-8 mini text-white/55"><div><div className="text-white text-sm tracking-[.18em]">MAKEWEBB</div><div className="mt-2">DIGITAL PRODUCT STUDIO</div></div><div>AI · WEB · DATA · EXPERIENCE</div><div className="flex gap-4"><a href="https://github.com/owaies" target="_blank" rel="noreferrer">GITHUB</a><a href="https://www.linkedin.com/in/mohammed-owaies-507b4a398" target="_blank" rel="noreferrer">LINKEDIN</a></div><div className="sm:text-right">© 2026 MAKEWEBB<br/>BUILT WITH INTENT.</div></footer></section>
    </main>
  </div>
}

function Founder(p:any){return <motion.article initial={{opacity:0,y:40}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.8}} className="group"><div className="relative aspect-[4/5] rounded-[28px] overflow-hidden border border-white/10 bg-white/5"><img src={p.img} alt={p.name} className="w-full h-full object-cover object-top grayscale group-hover:grayscale-0 group-hover:scale-[1.035] transition duration-700"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/10 to-transparent"/><div className="absolute left-6 right-6 bottom-6"><div className="mini text-white/55">FOUNDER / {p.role}</div><h3 className="mt-2 font-display text-3xl sm:text-4xl">{p.name}</h3><div className="mt-2 mini text-[#c8a5ff]">{p.focus}</div></div></div><div className="pt-5 flex flex-wrap items-center gap-4 mini text-white/55"><a href={p.portfolio} target="_blank" rel="noreferrer" className="text-white">PORTFOLIO ↗</a><a href={p.github} target="_blank" rel="noreferrer"><Github size={14} className="inline mr-1"/>GITHUB</a><a href={p.linkedin} target="_blank" rel="noreferrer"><Linkedin size={14} className="inline mr-1"/>LINKEDIN</a><a href={'mailto:'+p.email}><Mail size={14} className="inline mr-1"/>MAIL</a><a href={'tel:'+p.phone}><Phone size={14} className="inline mr-1"/>CALL</a></div></motion.article>}
