import React,{useEffect,useRef,useState}from'react';
import{AnimatePresence,motion,useMotionValue,useSpring}from'motion/react';
import{ArrowUpRight,Menu,X,Github,Linkedin,Mail,Phone}from'lucide-react';

const projects=[['01','AI JOB TRACKER','AI PRODUCT','Next.js · AI · Analytics','https://ai-job-application-tracker-rose.vercel.app'],['02','E-EXAMINER','EXAM PLATFORM','Web App · Assessments · Exams','https://e-examiner.vercel.app/'],['03','WORLD OBJECT DETECTOR','COMPUTER VISION','Python · Vision · Detection','https://world-object-detector.netlify.app/'],['04','SILSILA BURQA HOUSE','E-COMMERCE','Web · Commerce · Product Experience','https://silsilaburqahouse.web.app'],['05','HAND GESTURE CONTROLLER','COMPUTER VISION','Python · Hand Tracking · Interaction','https://handgesturecontroller.netlify.app/']];
const skills=['AI','MACHINE LEARNING','DATA','WEB','APPS','UI/UX','COMPUTER VISION','INTERACTIVE EXPERIENCES'];

function usePointer(enabled:boolean){
 const x=useMotionValue(0),y=useMotionValue(0);
 const sx=useSpring(x,{stiffness:80,damping:24}),sy=useSpring(y,{stiffness:80,damping:24});
 useEffect(()=>{if(!enabled)return;const f=(e:MouseEvent)=>{x.set((e.clientX/Math.max(1,innerWidth)-.5)*20);y.set((e.clientY/Math.max(1,innerHeight)-.5)*14)};window.addEventListener('mousemove',f,{passive:true});return()=>window.removeEventListener('mousemove',f)},[enabled,x,y]);
 return[sx,sy]as const;
}

function Device({i,interactive=true}:{i:number;interactive?:boolean}){return <motion.div className={'ref-device d'+i} whileHover={interactive?{y:-18,rotateY:i===1?0:5,rotateZ:i===0?-2:2}:undefined}><div className="device-screen"><small>{i===1?'MAKEWEBB':'MW / 00'+i}</small><b>{i===1?'SYSTEMS THAT ANSWER FIRST':i===2?'E-EXAMINER':'INTELLIGENT'}</b><span/></div></motion.div>}
function Chrome(){return <motion.div className="ref-chrome" animate={{rotateZ:[0,5,-4,0],rotateX:[0,8,-6,0],y:[0,-16,0]}} transition={{duration:8,repeat:Infinity,ease:'easeInOut'}}><div/></motion.div>}
function Founder({name,role,focus,img,portfolio,github,linkedin,email,phone}:{name:string;role:string;focus:string;img:string;portfolio:string;github:string;linkedin:string;email:string;phone:string}){return <article className="ref-founder"><div className="founder-image"><img src={img}alt={name}loading="lazy"onError={e=>{e.currentTarget.style.opacity='0'}}/></div><div className="founder-info"><span className="ref-meta">FOUNDER</span><h3>{name}</h3><p>{role} · {focus}</p><div><a href={portfolio}target="_blank"rel="noreferrer">PORTFOLIO ↗</a><a href={github}target="_blank"rel="noreferrer"aria-label="GitHub"><Github size={14}/></a><a href={linkedin}target="_blank"rel="noreferrer"aria-label="LinkedIn"><Linkedin size={14}/></a><a href={'mailto:'+email}aria-label="Email"><Mail size={14}/></a><a href={'tel:'+phone}aria-label="Phone"><Phone size={14}/></a></div></div></article>}

function Work({interactive=true}:{interactive?:boolean}){
 const r=useRef<HTMLDivElement>(null);const[t,setT]=useState(0);const raf=useRef<number|null>(null);
 useEffect(()=>{
  const update=()=>{raf.current=null;if(!r.current)return;const rect=r.current.getBoundingClientRect();const start=rect.top+window.scrollY;const travel=Math.max(1,r.current.offsetHeight-window.innerHeight);const p=Math.max(0,Math.min(1,(window.scrollY-start)/travel));setT(p)};
  const onScroll=()=>{if(raf.current===null)raf.current=requestAnimationFrame(update)};const onResize=()=>update();
  window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onResize,{passive:true});update();
  return()=>{window.removeEventListener('scroll',onScroll);window.removeEventListener('resize',onResize);if(raf.current!==null)cancelAnimationFrame(raf.current)};
 },[]);
 const x=38-t*72;
 return <section id="projects"ref={r}className="match-work"><div className="match-sticky"><div className="ref-meta">SELECTED WORK</div><div className="match-canvas"><div className="match-track"style={{transform:`translate3d(${x}vw,0,0)`}}>{projects.map((p,i)=>{const distance=Math.abs(i-2);const scale=i===2?1:.84-.08*Math.min(2,distance);const opacity=1-.14*Math.min(2,distance);return <motion.a href={p[4]}target="_blank"rel="noreferrer"className={'match-card '+(i===2?'active':'')}key={p[0]}style={{transform:`translateY(${Math.sin(i*1.8+t*3)*12}px) scale(${scale}) rotate(${(i-2)*1.5}deg)`,opacity}}whileHover={interactive?{scale:scale*1.035,rotateX:2,rotateY:-2,zIndex:5}:undefined}><small>#{p[0]}</small><h3>{p[1]}</h3><p>{p[2]} <i>|</i> {p[3]}</p><div className="preview"><div><span>{i===0?'AI':i===1?'EXAM':i===2?'NOVA':'MW'}</span><b>{p[1]}</b></div></div><strong>VIEW PROJECT <ArrowUpRight size={12}/></strong></motion.a>})}</div></div><div className="archive">SEE THE FULL <b>ARCHIVE ↗</b></div></div></section>
}

export default function ReferenceMatch(){
 const[menu,setMenu]=useState(false),[loading,setLoading]=useState(true),[interactive,setInteractive]=useState(false);const[mx,my]=usePointer(interactive);
 useEffect(()=>{const media=window.matchMedia('(hover: hover) and (pointer: fine)');const sync=()=>setInteractive(media.matches);sync();media.addEventListener?.('change',sync);return()=>media.removeEventListener?.('change',sync)},[]);
 useEffect(()=>{if(!menu)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',esc);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',esc)}},[menu]);
 const go=(id:string)=>{const el=document.getElementById(id);if(!el)return;const top=Math.max(0,el.getBoundingClientRect().top+window.scrollY-72);window.scrollTo({top,behavior:'smooth'});setMenu(false)};
 return <div className="match-page">
  <AnimatePresence>{loading&&<motion.div key="loader"className="match-loader"initial={{opacity:1}}animate={{opacity:1}}exit={{opacity:0}}transition={{duration:.45}}><div><span>MW</span><b>MAKEWEBB</b><small>DIGITAL PRODUCT STUDIO</small></div></motion.div>}</AnimatePresence>
  <motion.header className="match-nav"style={interactive?{x:mx,y:my}:undefined}><button onClick={()=>go('hero')}className="brand"aria-label="MakeWebb home"><span>MW</span>MAKEWEBB</button><nav>{[['projects','WORK'],['capabilities','CAPABILITIES'],['founders','FOUNDERS'],['contact','CONTACT']].map(([id,label])=><button key={id}onClick={()=>go(id)}>{label}</button>)}</nav><button className="nav-start"onClick={()=>go('contact')}>GET STARTED</button><button className="menu-btn"onClick={()=>setMenu(true)}aria-label="Open menu"><Menu size={16}/></button></motion.header>
  <AnimatePresence>{menu&&<motion.div className="match-menu"initial={{opacity:0,x:20}}animate={{opacity:1,x:0}}exit={{opacity:0,x:20}}transition={{duration:.28}}><button onClick={()=>setMenu(false)}aria-label="Close menu"><X/></button><div>{['projects','capabilities','founders','contact'].map(x=><button key={x}onClick={()=>go(x)}>{x.toUpperCase()}</button>)}</div></motion.div>}</AnimatePresence>
  <main>
   <section id="hero"className="match-hero"><div className="hero-grid"><div className="hero-copy"><span className="ref-meta white">MW / 001 · DIGITAL PRODUCT STUDIO</span><h1>SYSTEMS THAT<br/><em>ANSWER FIRST.</em></h1><p>Intelligent products, web experiences and data systems built for the next layer of the web.</p><div><button onClick={()=>go('projects')}>VIEW WORK ↗</button><button onClick={()=>go('founders')}>MEET THE FOUNDERS ↓</button></div></div><motion.div className="device-stage"style={interactive?{x:mx,y:my}:undefined}><Device i={0}interactive={interactive}/><Device i={1}interactive={interactive}/><Device i={2}interactive={interactive}/></motion.div></div><div className="star">✦</div><div className="hero-bottom ref-meta white"><span>AI · WEB · DATA · EXPERIENCE</span><span>SCROLL / EXPLORE</span></div></section>
   <section className="match-light manifesto"><span className="ref-meta">MW / 002 · STUDIO</span><div className="manifesto-copy"><h2>WE DON'T JUST<br/>BUILD WEBSITES.</h2><div className="manifesto-devices"><Device i={0}interactive={interactive}/><Device i={1}interactive={interactive}/><Device i={2}interactive={interactive}/></div></div></section>
   <section id="capabilities"className="match-dark capability"><span className="ref-meta white">MW / 003 · CAPABILITIES</span><div className="cap-head">BEYOND<br/><span>EVERY LIMIT.</span></div><div className="cap-grid">{skills.map((s,i)=><motion.div key={s}initial={{opacity:0,y:24}}whileInView={{opacity:1,y:0}}viewport={{once:true,amount:.15}}transition={{duration:.7,delay:i*.04}}><small>0{i+1}</small><b>{s}</b><span>{i%2?'SYSTEMS':'PRODUCT'} · 2026</span></motion.div>)}</div></section>
   <Work interactive={interactive}/>
   <section id="founders"className="match-light founders"><span className="ref-meta">MW / 005 · FOUNDERS</span><div className="founder-grid"><Founder name="MOHAMMED OWAIES"role="AI / ML ENGINEER"focus="AI · ML · DATA"img="/founders/owaies.png"portfolio="https://owaies-portfolio.base44.app"github="https://github.com/owaies"linkedin="https://www.linkedin.com/in/mohammed-owaies-507b4a398"email="owaies786@gmail.com"phone="7619329863"/><Founder name="MOHAMMED AFAF HASSAN"role="WEB DEVELOPER"focus="WEB · APPS · UI/UX"img="/founders/afaf.png"portfolio="https://afaf.base44.app"github="https://github.com/afaf-app"linkedin="https://www.linkedin.com/in/mansafaf"email="kingahassan786@gmail.com"phone="8073818817"/></div></section>
   <section className="match-dark statement"><span className="ref-meta white">MW / 006 · STUDIO</span><h2>BUILD<br/><span>BEYOND</span><br/>EVERY LIMIT.</h2></section>
   <section className="match-purple tech"><span className="ref-meta white">MW / 007 · TECHNOLOGY</span><div>{['AI','ML','DATA','PYTHON','NEXT.JS','REACT','JAVASCRIPT','COMPUTER VISION','UI/UX','WEB','APPS','AUTOMATION'].map(x=><b key={x}>{x}</b>)}</div></section>
   <section id="contact"className="match-cta"><div><span className="ref-meta white">MW / 008 · CONTACT</span><h2>BUILD BEYOND<br/><em>EVERY LIMIT.</em></h2><p>Have an idea? Let's build the experience it deserves.</p><button onClick={()=>location.href='mailto:owaies786@gmail.com'}>START A PROJECT ↗</button></div><Chrome/></section>
   <footer className="match-footer"><b>MAKEWEBB</b><span>DIGITAL PRODUCT STUDIO</span><span>AI · WEB · DATA · EXPERIENCE</span><span>© 2026 MAKEWEBB</span></footer>
  </main>
 </div>
}
